## Deliverable 2. Create a Customer Travel Destinations Map.

In [13]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [14]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Ulladulla,AU,2021-05-31 16:14:14,-35.3500,150.4667,47.08,70,28,5.39,scattered clouds
1,1,Opuwo,NaN,2021-05-31 16:14:14,-18.0607,13.8400,76.77,16,72,7.99,broken clouds
2,2,Severo-Yeniseyskiy,RU,2021-05-31 16:14:14,60.3725,93.0408,47.82,64,99,5.68,overcast clouds
3,3,Cayenne,GF,2021-05-31 16:11:50,4.9333,-52.3333,80.10,88,75,3.00,moderate rain
4,4,Constitucion,CL,2021-05-31 16:14:15,-35.3333,-72.4167,62.49,83,89,5.46,overcast clouds

In [15]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 80
What is the maximum temperature you would like for your trip? 100

In [16]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Cayenne,GF,2021-05-31 16:11:50,4.9333,-52.3333,80.10,88,75,3.00,moderate rain
8,8,Hilo,US,2021-05-31 16:11:12,19.7297,-155.0900,82.27,94,90,4.61,light rain
11,11,Vila Velha,BR,2021-05-31 16:12:07,-20.3297,-40.2925,85.96,78,40,4.00,scattered clouds
16,16,Beyneu,KZ,2021-05-31 16:14:18,45.3167,55.2000,80.49,37,1,17.34,clear sky
22,22,Pitimbu,BR,2021-05-31 16:14:20,-7.4706,-34.8086,82.99,76,40,13.13,scattered clouds
30,30,Saint-Georges,GD,2021-05-31 16:14:21,12.0564,-61.7485,83.88,74,40,21.85,scattered clouds
31,31,Carutapera,BR,2021-05-31 16:14:22,-1.1950,-46.0200,88.00,57,27,7.27,scattered clouds
32,32,Aripuana,BR,2021-05-31 16:11:33,-9.1667,-60.6333,92.88,36,67,3.20,broken clouds
33,33,Korla,CN,2021-05-31 16:14:22,41.7597,86.1469,81.64,17,99,4.90,overcast clouds
34,34,Riberalta,BO,2021-05-31 16:14:23,-10.9833,-66.1000,86.94,60,100,2.55,overcast clouds

In [17]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

# Alternative method:
# preferred_cities_df.isnull().sum()

City_ID                161
City                   161
Country                161
Date                   161
Lat                    161
Lng                    161
Max Temp               161
Humidity               161
Cloudiness             161
Wind Speed             161
Current Description    161
dtype: int64

In [18]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Cayenne,GF,2021-05-31 16:11:50,4.9333,-52.3333,80.10,88,75,3.00,moderate rain
8,8,Hilo,US,2021-05-31 16:11:12,19.7297,-155.0900,82.27,94,90,4.61,light rain
11,11,Vila Velha,BR,2021-05-31 16:12:07,-20.3297,-40.2925,85.96,78,40,4.00,scattered clouds
16,16,Beyneu,KZ,2021-05-31 16:14:18,45.3167,55.2000,80.49,37,1,17.34,clear sky
22,22,Pitimbu,BR,2021-05-31 16:14:20,-7.4706,-34.8086,82.99,76,40,13.13,scattered clouds
...,...,...,...,...,...,...,...,...,...,...,...
691,691,Dawei,MM,2021-05-31 16:17:56,14.0833,98.2000,80.33,88,11,3.31,few clouds
693,693,Jati,PK,2021-05-31 16:17:57,24.3539,68.2671,86.25,72,1,18.99,clear sky
694,694,Gizo,SB,2021-05-31 16:17:57,-8.1030,156.8419,80.85,84,87,19.10,light rain
695,695,Santa Rosa,PH,2021-05-31 16:17:57,14.3122,121.1114,85.98,73,99,1.14,overcast clouds
700,700,Ebejico,CO,2021-05-31 16:17:59,6.3260,-75.7683,82.62,59,80,1.79,broken clouds

In [19]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Cayenne,GF,80.10,moderate rain,4.9333,-52.3333,
8,Hilo,US,82.27,light rain,19.7297,-155.0900,
11,Vila Velha,BR,85.96,scattered clouds,-20.3297,-40.2925,
16,Beyneu,KZ,80.49,clear sky,45.3167,55.2000,
22,Pitimbu,BR,82.99,scattered clouds,-7.4706,-34.8086,
30,Saint-Georges,GD,83.88,scattered clouds,12.0564,-61.7485,
31,Carutapera,BR,88.00,scattered clouds,-1.1950,-46.0200,
32,Aripuana,BR,92.88,broken clouds,-9.1667,-60.6333,
33,Korla,CN,81.64,overcast clouds,41.7597,86.1469,
34,Riberalta,BO,86.94,overcast clouds,-10.9833,-66.1000,

In [20]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    # 6c. Get latitude and longitude from DataFrame
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [21]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(how = 'any')

In [22]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [23]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [24]:
# 11a. Add a marker layer for each city to the map. 

locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))