## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Cayenne,GF,80.10,moderate rain,4.9333,-52.3333,Hôtel Le Dronmi
1,8,Hilo,US,82.27,light rain,19.7297,-155.0900,Hilo Hawaiian Hotel
2,11,Vila Velha,BR,85.96,scattered clouds,-20.3297,-40.2925,Quality Suites Vila Velha
3,16,Beyneu,KZ,80.49,clear sky,45.3167,55.2000,NUR
4,22,Pitimbu,BR,82.99,scattered clouds,-7.4706,-34.8086,Reserva do Abiaí

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temperature </dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Cayenne,GF,80.10,moderate rain,4.9333,-52.3333,Hôtel Le Dronmi
1,8,Hilo,US,82.27,light rain,19.7297,-155.0900,Hilo Hawaiian Hotel
2,11,Vila Velha,BR,85.96,scattered clouds,-20.3297,-40.2925,Quality Suites Vila Velha
3,16,Beyneu,KZ,80.49,clear sky,45.3167,55.2000,NUR
4,22,Pitimbu,BR,82.99,scattered clouds,-7.4706,-34.8086,Reserva do Abiaí
...,...,...,...,...,...,...,...,...
156,691,Dawei,MM,80.33,few clouds,14.0833,98.2000,Hotel Dawei
157,693,Jati,PK,86.25,clear sky,24.3539,68.2671,Cafe Lala Rehan Restaurant
158,694,Gizo,SB,80.85,light rain,-8.1030,156.8419,Imagination Island
159,695,Santa Rosa,PH,85.98,overcast clouds,14.3122,121.1114,Erlyn’s Sta Rosa City Home
160,700,Ebejico,CO,82.62,broken clouds,6.3260,-75.7683,HOTEL HEVEXICO

In [19]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df.City =='Colombo']
vacation_end = vacation_df.loc[vacation_df.City =='Colombo']
vacation_stop1 = vacation_df.loc[vacation_df.City =='Galle']
vacation_stop2 = vacation_df.loc[vacation_df.City =='Matara'] 
vacation_stop3 = vacation_df.loc[vacation_df.City =='Hambantota']

In [20]:
vacation_start.dtypes

City_ID                  int64
City                    object
Country                 object
Max Temp               float64
Current Description     object
Lat                    float64
Lng                    float64
Hotel Name              object
dtype: object

In [21]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()[0]
end = vacation_end[["Lat", "Lng"]].to_numpy()[0]
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()[0]
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()[0]
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()[0]

In [23]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
route = gmaps.directions_layer(start, end, waypoints=[stop1,stop2, stop3], 
                               travel_mode="DRIVING" or "BICYCLING" or "WALKING")
fig.add_layer(route)

fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,552,Colombo,LK,81.21,overcast clouds,6.9319,79.8478,Galle Face Hotel
1,481,Galle,LK,81.28,broken clouds,6.0367,80.2170,Amangalla
2,262,Matara,LK,80.51,overcast clouds,5.9485,80.5353,Amaloh Boutique Resort
3,122,Hambantota,LK,81.27,broken clouds,6.1241,81.1185,Bungalow 63

In [25]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""
# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [26]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))